export PATH=$HOME/Projects/Work/cr-ops-scripts:$PATH

export TERM=xterm-256color
export EDITOR=vim
export HOMEBREW_BUNDLE_NO_LOCK=true
export PYENV_VIRTUALENV_DISABLE_PROMPT=true
export SHOW_AWS_PROMPT=false
export ZSH=$HOME/.oh-my-zsh

ZSH_CUSTOM=$HOME/.zsh/custom
ZSH_THEME="dotfiles"
DISABLE_AUTO_TITLE=true
COMPLETION_WAITING_DOTS=true

plugins=(
  git
  aws
  knife
  kitchen  
  pyenv
)

FPATH=/usr/local/share/zsh-completions:$FPATH

source $ZSH/oh-my-zsh.sh

complete -C /usr/local/bin/terraform terraform
complete -C /usr/local/bin/packer packer
complete -C /usr/local/bin/vault vault

alias cat="ccat"
alias ca="/bin/cat"
alias git="noglob git"
alias config-git="$EDITOR $HOME/.gitconfig"
alias config-git-ignore="$EDITOR $HOME/.gitignore"
alias config-kitchen="$EDITOR $HOME/.kitchen/config.yml"
alias config-aws="$EDITOR $HOME/.aws/config"
alias config-aws-creds="$EDITOR $HOME/.aws/credentials"
alias config-zsh="$EDITOR $HOME/.zshrc"
alias config-zsh-theme="$EDITOR $HOME/.zsh/custom/themes/dotfiles.zsh-theme"
alias config-vim="$EDITOR $HOME/.vimrc"
alias wmip="curl ipv4.icanhazip.com"
alias aws-whoami="aws sts get-caller-identity"
alias gcca="gcloud config configurations activate"
alias sbp="cd $HOME/Projects/personal/sandbox"
alias sbw="cd $HOME/Projects/work/sandbox"
alias copy-ssh-key="cat $HOME/.ssh/id_rsa.pub | pbcopy"
alias update-brew-bundle="brew bundle dump --global --force"
alias update-brew="brew bundle cleanup --force --global && brew update && brew upgrade && brew cleanup"
alias update-all="upgrade_oh_my_zsh && update-brew"
alias cr-switchrole=". cr-switchrole"

