---
driver:
  name: ec2
  region: eu-west-1
  interface: public
  shared_credentials_profile: lab
  instance_type: t3.medium 
  subnet_filter:
    tag:   Name
    value: mh-lab-public
  security_group_filter:
    tag:   Name
    value: mh-lab-public
  tags:
    Name:  mh-test-kitchen
    Owner: MH 

verifier:
  name: inspec
  reporter:
  - cli
  - junit:.kitchen/results/%{platform}_%{suite}_inspec.xml
